SELECT_ALL_YEARS_BUTTON = "select-all-years-button"
SELECT_ALL_MONTHS_BUTTON = "select-all-months-button"
SELECT_ALL_CATEGORIES_BUTTON = "select-all-categories-button"
CATEGORIES_DROPDOWN = "categories-dropdown"
YEARS_DROPDOWN = "years-dropdown"
MONTHS_DROPDOWN = "months-dropdown"
BAR_CHART = "bar-chart"
